version: "3"
services:

  app:
    build: ./app
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - PORT=80

  frontend:
    build: ./frontend
    ports:
      - "8081:5000"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
