version: "3"
services:
  app:
    build: ./app
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - PORT=80
  db:
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD