version: "3"
services:

  backend:
    container_name: olengu_backend
    build: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/backend
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - PORT=80

  frontend:
    container_name: olengu_frontend
    build: ./frontend
    ports:
      - "8081:5000"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  gateway:
    container_name: olengu_gateway
    build: ./gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/build:/var/www/html
      - ./gateway/nginx-config:/etc/nginx/sites-enabled/default

  db:
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
